function metadata = WyoRS_metadata()

% ---- Function where variable names, description and units are defined
% Information extracted from the Wyoming University Website 
%
% (c) 2018, Pablo Saavedra G., University of Bergen
% See LICENCE.TXT
% ---------------------------------------------------------------------

% Metadata for the profile variables:
%    Parameter 	Description 	Units
Profile={...
    'PRES', 'Atmospheric Pressure', 'hPa';...
    'HGHT', 'Geopotential Height','m';...
    'TEMP', 'Temperature','°C';...
    'DWPT', 'Dewpoint Temperature','°C';...
    'FRPT', 'Frost Point Temperature','°C';...
    'RELH', 'Relative Humidity','%';...
    'RELI', 'Relative Humidity with respect to Ice','%';...
    'MIXR', 'Mixing Ratio','g/kg';...
    'DRCT', 'Wind Direction','degrees true';...
    'SKNT', 'Wind Speed','knot';...
    'THTA', 'Potential Temperature','K';...
    'THTE', 'Equivalent Potential Temperature','K';...
    'THTV', 'Virtual Potential Temperature','K'
                    };

% Metadata for the sounding Indices variables:
NameIndices={'OBST','SLAT','SLON','SELV','SHOW','LIFT','LFTV',...
             'SWET','KINX','CTOT','VTOT','TTOT','CAPE',...
             'CAPV','CINS','CINV','EQLV','EQTV','LFCT',...
             'LFCV','BRCH','BRCV','LCLT','LCLP','MLTH',...
             'MLMR','THTK','PWAT'};

Indices={'Observation time',...
                    'Station latitude',...
                    'Station longitude',...
                    'Station elevation',...
                    'Showalter index',...
                    'Lifted index',...
                    'LIFT computed using virtual temperature',...
                    'SWEAT index',...
                    'K index',...
                    'Cross totals index',...
                    'Vertical totals index',...
                    'Totals totals index',...
                    'Convective Available Potential Energy',...
                    'CAPE using virtual temperature',...
                    'Convective Inhibition',...
                    'CINS using virtual temperature',...
                    'Equilibrium level',...  % (hPa)
                    'Equilibrium level using virtual temperature',...
                    'Level of Free Convection',... % (hPa)
                    'LFCT using virtual temperature',...
                    'Bulk Richardson Number',...
                    'Bulk Richardson Number using CAPV',...
                    'Temp [K] of the Lifted Condensation Level',...
                    'Pres [hPa] of the Lifted Condensation Level',...
                    'Mean mixed layer potential temperature',...
                    'Mean mixed layer mixing ratio',...
                    '1000 hPa to 500 hPa thickness',...
                    'Precipitable water [mm] for entire sounding'
                   };

UnitsIndices={'[YYMMDD.HH]',... % Obs time
              'deg North',...
              'deg East',...
              'm. a.g.l.',...
              '°C',... % ?
              '°C',... % Lifted Index
              '°C',...
              '[]',... % SWEAT index
              '°C',.... % K-index
              '°C',...  % Corss totals
              '°C',...  % vertical totals
              '°C',...  % Total totals
              'J/kg',...  % CAPE
              'J/kg',...  % CAPEV
              'J/kg',...  % Conv. Inhibition
              'J/kg',...  % Conv. Inhibition Virtual T
              'hPa',...  % Equi. level
              'hPa',...  % Equi. levet virtual T.
              'hPa',...  % level free conv.
              'hPa',...  % level free conv. virtual T.
              '[]',...  % Richardson Num.
              '[]',...  %  Richardson Num virtual T.
              'K',...  % T. Lifted conden. level
              'hPa',... %  P. Lifted conden. level
              'K',...  % Mean mixed lay. P.T.
              'g/kg',...  % Mean mixes lay. M.R.
              'm',...  % ??
              'mm',... % total Precip water 
             };

% ---------------
% Gathering the output variable:
metadata.PROFILE = Profile;  %Meta;
metadata.RSINDICES = cat(2,NameIndices',...
                         Indices',... %DescriptionIndices',...
                         UnitsIndices');

return;
end
